### ISSUE TITLE
Investigate correlation trends

### ISSUE THREAD

**Issue by silvs110** [padaiyal/jAayvalar#17]
- [x] <b>Description</b>
    Understand ways to apply correlation formula for two dimensional data. Understand the visual trends for different functions we will be correlated with.
- [x] <b>Use cases</b>
N/A
- [x] <b>Proposed design</b>
N/A
- [x] <b>Alternative design approaches</b>
N/A
- [x] <b>Workaround</b>
N/A
- [x] <b>Additional information</b>
N/A

**Comment by the-c0d3br34k3r** [comment]
Hey @silvs110,
Can you add the information you've collected to this issue.
